export const MARKET_GROUPS: Record<string, string[]> = {
  Popular: ["AAPL", "TSLA", "NVDA", "MSFT", "AMZN", "GOOGL", "META", "SPY", "NFLX", "AMD"],
  Tech: ["AAPL", "MSFT", "NVDA", "AMD", "INTC", "ORCL", "CRM", "SNOW", "PLTR", "UBER"],
  Finance: ["JPM", "BAC", "GS", "MS", "V", "MA", "BRK-B", "WFC", "AXP", "C"],
  ETFs: ["SPY", "QQQ", "VTI", "IWM", "GLD", "TLT", "ARKK", "DIA", "XLK", "XLF"],
  Energy: ["XOM", "CVX", "COP", "SLB", "OXY", "MPC", "PSX", "VLO", "HAL", "DVN"],
  Healthcare: ["JNJ", "UNH", "PFE", "ABBV", "MRK", "BMY", "LLY", "AMGN", "GILD", "CVS"],
  Consumer: ["AMZN", "WMT", "HD", "NKE", "SBUX", "MCD", "TGT", "COST", "LOW", "DG"],
};

export const COMPANY_NAMES: Record<string, string> = {
  AAPL: "Apple Inc.",
  TSLA: "Tesla Inc.",
  NVDA: "NVIDIA Corp.",
  MSFT: "Microsoft Corp.",
  AMZN: "Amazon.com Inc.",
  GOOGL: "Alphabet Inc.",
  META: "Meta Platforms",
  SPY: "S&P 500 ETF",
  AMD: "Advanced Micro Devices",
  INTC: "Intel Corp.",
  ORCL: "Oracle Corp.",
  CRM: "Salesforce",
  SNOW: "Snowflake Inc.",
  PLTR: "Palantir Technologies",
  UBER: "Uber Technologies",
  NFLX: "Netflix Inc.",
  JPM: "JPMorgan Chase",
  BAC: "Bank of America",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  V: "Visa Inc.",
  MA: "Mastercard Inc.",
  "BRK-B": "Berkshire Hathaway",
  WFC: "Wells Fargo",
  AXP: "American Express",
  C: "Citigroup Inc.",
  QQQ: "Nasdaq 100 ETF",
  VTI: "Vanguard Total Market",
  IWM: "Russell 2000 ETF",
  GLD: "SPDR Gold Shares",
  TLT: "iShares 20+ Year Treasury",
  ARKK: "ARK Innovation ETF",
  DIA: "Dow Jones ETF",
  XLK: "Technology Select SPDR",
  XLF: "Financial Select SPDR",
  XOM: "ExxonMobil Corp.",
  CVX: "Chevron Corp.",
  COP: "ConocoPhillips",
  SLB: "SLB",
  OXY: "Occidental Petroleum",
  MPC: "Marathon Petroleum",
  PSX: "Phillips 66",
  VLO: "Valero Energy",
  HAL: "Halliburton Co.",
  DVN: "Devon Energy",
  JNJ: "Johnson & Johnson",
  UNH: "UnitedHealth Group",
  PFE: "Pfizer Inc.",
  ABBV: "AbbVie Inc.",
  MRK: "Merck & Co.",
  BMY: "Bristol-Myers Squibb",
  LLY: "Eli Lilly & Co.",
  AMGN: "Amgen Inc.",
  GILD: "Gilead Sciences",
  CVS: "CVS Health",
  WMT: "Walmart Inc.",
  HD: "Home Depot",
  NKE: "Nike Inc.",
  SBUX: "Starbucks Corp.",
  MCD: "McDonald's Corp.",
  TGT: "Target Corp.",
  COST: "Costco Wholesale",
  LOW: "Lowe's Cos.",
  DG: "Dollar General",
};

export function getCompanyName(symbol: string) {
  return COMPANY_NAMES[symbol] ?? symbol;
}
